spring.config.import=optional:file:.env[.properties]
spring.application.name=UploadService
server.port=${PORT}
server.forward-headers-strategy=framework

# Eureka Client Configuration
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL}

# Local Storage Path Configuration
storage.local.path=${VIDEO_STORAGE_PATH}

# SpringDoc OpenAPI configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true
