spring.config.import=optional:file:.env[.properties]
spring.application.name=UploadService
server.port=${PORT}

# Eureka Client Configuration
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL}

# Local Storage Path Configuration
storage.local.path=${VIDEO_STORAGE_PATH}
