spring.config.import=optional:file:.env[.properties]
spring.application.name=UPLOAD-SERVICE
server.port=${PORT}
server.forward-headers-strategy=framework

# Eureka Client Configuration
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL}

# Local Storage Path Configuration
storage.local.path=${VIDEO_STORAGE_PATH}
storage.thumbnail.path=${THUMBNAIL_STORAGE_PATH}

# SpringDoc OpenAPI configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true

# Custom logging date-time pattern
logging.pattern.dateformat=yyyy-MM-dd HH:mm:ss.SSS

# Multipart File Upload Limits
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
server.tomcat.max-swallow-size=-1
