spring.config.import=optional:file:.env[.properties]
spring.application.name=EurekaServer
server.port=${PORT}

# Eureka Server configuration
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL}
